[package]
name = "rlua-lua51-sys"
version = "0.1.7"
keywords = ["bindings", "lua"]
categories = ["external-ffi-bindings"]
description = "Bindings to lua's C API"
repository = "https://github.com/amethyst/rlua"
readme = "README.md"
edition = "2018"
links = "lua5.1"
build = "build.rs"
license = "MIT"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3.24"

[features]
default = []
luajit-pkg-config = []
lua51-pkg-config = []
static = []
lua-no-oslib = []

[badges.maintenance]
status = "deprecated"
